{
  parserClass="com.github.xepozz.gitcodeowners.language.parser.GitCodeownersParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="GitCodeowners"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.xepozz.gitcodeowners.language.psi"
  psiImplPackage="com.github.xepozz.gitcodeowners.language.psi.impl"

  elementTypeHolderClass="com.github.xepozz.gitcodeowners.language.psi.GitCodeownersTypes"
  elementTypeClass="com.github.xepozz.gitcodeowners.language.psi.GitCodeownersElementType"
  tokenTypeClass="com.github.xepozz.gitcodeowners.language.psi.GitCodeownersTokenType"

//  psiImplUtilClass="com.github.xepozz.gitcodeowners.language.psi.impl.GitCodeownersImplUtil"
}

gitcodeownersFile ::= item_*

private item_ ::= (definition | COMMENT | EOL)

definition ::= unary_definition
unary_definition ::= pattern parameter+
pattern ::= TEXT
parameter ::= TEXT
//
//cronExpression ::= (SCHEDULE COMMAND)
//{
//    pin=1
//    implements=["com.intellij.psi.NavigatablePsiElement"]
//}
//
//variableDefinition ::= (VARIABLE_NAME EQUAL_SIGN VARIABLE_VALUE)
//{
//    pin=1
//    implements=["com.intellij.psi.NavigatablePsiElement"]
//    extends="com.github.xepozz.gitcodeowners.language.psi.impl.GitCodeownersVariableBaseImpl"
//}
//VARIABLE_NAME ::= IDENTIFIER
//VARIABLE_VALUE ::= CONTENT
//
//SCHEDULE ::= TIME_POINTER TIME_POINTER TIME_POINTER TIME_POINTER TIME_POINTER
//{
//    pin=1
//    implements=["com.intellij.psi.NavigatablePsiElement"]
//    extends="com.github.xepozz.gitcodeowners.language.psi.impl.GitCodeownersScheduleBaseImpl"
//}
//
//TIME_POINTER ::= TIME_LIST
//TIME_LIST ::= TIME_LIST_ITEM (COMMA TIME_LIST_ITEM)*
//
//TIME_LIST_ITEM ::= TIME_RANGE_STEP | TIME_RANGE | TIME_EXACT | TIME_ANY
//
//TIME_RANGE_STEP ::= (TIME_RANGE | TIME_EXACT | TIME_ANY) SLASH NUMBER
//{
//    pin=2
//}
//
//TIME_RANGE ::= NUMBER HYPHEN NUMBER
//{
//    pin=2
//    implements=["com.intellij.psi.NavigatablePsiElement"]
//    extends="com.github.xepozz.gitcodeowners.language.psi.impl.GitCodeownersTimeRangeBaseImpl"
//    methods=[getFirst getSecond getIntRange]
//}
//TIME_ANY ::= STAR
//TIME_EXACT ::= NUMBER
//
//COMMAND ::= CONTENT
//{
//    implements=["com.intellij.psi.NavigatablePsiElement" "com.intellij.psi.PsiLanguageInjectionHost"]
//    extends="com.github.xepozz.gitcodeowners.language.psi.impl.GitCodeownersCommandBaseImpl"
//}

COMMENT ::= SINGLE_COMMENT
